In [4]:
# Importar la librería
import numpy as np
# Crea una matriz bidimensional (array) llamada ventas_mensuales con una dimensión de 12 filas (representando los meses del año) y 4 columnas (representando los productos vendidos). Los valores de la matriz representarán las ventas mensuales de cada producto.
ventas_mensuales = np.array([     [1200, 1500, 800, 2500],     [1800, 1600, 900, 2800],     [1500, 1400, 950, 2600],     [1300, 1700, 850, 2700],     [2000, 1800, 950, 2900],     [1700, 1600, 900, 2700],     [1400, 1300, 850, 2500],     [1600, 1400, 1000, 2600],     [1800, 1700, 950, 2900],     [1900, 1500, 850, 2800],     [1700, 1600, 900, 2600],     [2100, 1800, 1000, 3000] ])
# Imprime la matriz ventas_mensuales para verificar su contenido
print(ventas_mensuales)
# Calcula el total de ventas por producto sumando los valores de cada columna utilizando la función sum de NumPy.
total_ventas_productos = np.sum(ventas_mensuales, axis=0)
# Imprime el total de ventas por producto
print(total_ventas_productos)


StatementMeta(SPK02, 0, 5, Finished, Available)

[[1200 1500  800 2500]
 [1800 1600  900 2800]
 [1500 1400  950 2600]
 [1300 1700  850 2700]
 [2000 1800  950 2900]
 [1700 1600  900 2700]
 [1400 1300  850 2500]
 [1600 1400 1000 2600]
 [1800 1700  950 2900]
 [1900 1500  850 2800]
 [1700 1600  900 2600]
 [2100 1800 1000 3000]]
[20000 18900 10900 32600]


In [5]:
# Importar NumPy
import numpy as np

# Creación de una matriz bidimensional (array) llamada "matriz_3x3" con una dimensión de 3 filas y 3 columnas.
# Los valores de la matriz deben ir de 0 a 8. Utilizar la función "arange" de NumPy para generar los valores de forma consecutiva.
# Crear una matriz bidimensional 3x3
matriz_3x3 = np.arange(9).reshape(3, 3)

# Imprimir la matriz "matriz_3x3" para verificar su contenido.
print(matriz_3x3)

StatementMeta(SPK02, 1, 2, Finished, Available)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
# Creación de una matriz identidad de 6x6 llamada "matriz_identidad" utilizando la función "identity".
# Esta función creará una matriz cuadrada con unos en la diagonal principal y ceros en el resto de los elementos.
# Crear una matriz identidad de 6x6
matriz_identidad = np.identity(6)

# Imprimir la matriz "matriz_identidad" para verificar su contenido.
print(matriz_identidad)

StatementMeta(SPK02, 1, 3, Finished, Available)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
