In [7]:
# Importar la librería
import numpy as np
# Crea una matriz bidimensional (array) llamada ventas_mensuales con una dimensión de 12 filas (representando los meses del año) y 4 columnas (representando los productos vendidos). Los valores de la matriz representarán las ventas mensuales de cada producto.
ventas_mensuales = np.array([     [1200, 1500, 800, 2500],     [1800, 1600, 900, 2800],     [1500, 1400, 950, 2600],     [1300, 1700, 850, 2700],     [2000, 1800, 950, 2900],     [1700, 1600, 900, 2700],     [1400, 1300, 850, 2500],     [1600, 1400, 1000, 2600],     [1800, 1700, 950, 2900],     [1900, 1500, 850, 2800],     [1700, 1600, 900, 2600],     [2100, 1800, 1000, 3000] ])
# Imprime la matriz ventas_mensuales para verificar su contenido
print(ventas_mensuales)
# Calcula el total de ventas por producto sumando los valores de cada columna utilizando la función sum de NumPy.
total_ventas_productos = np.sum(ventas_mensuales, axis=0)
# Imprime el total de ventas por producto
print(total_ventas_productos)

StatementMeta(SPK02, 1, 4, Finished, Available)

[[1200 1500  800 2500]
 [1800 1600  900 2800]
 [1500 1400  950 2600]
 [1300 1700  850 2700]
 [2000 1800  950 2900]
 [1700 1600  900 2700]
 [1400 1300  850 2500]
 [1600 1400 1000 2600]
 [1800 1700  950 2900]
 [1900 1500  850 2800]
 [1700 1600  900 2600]
 [2100 1800 1000 3000]]
[20000 18900 10900 32600]
